services:
  deadbot:
    image: deadbot:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      IMPORT_FILES: ${IMPORT_FILES}
      ENGLISH_ONLY: ${ENGLISH_ONLY}
      DECOMPILE: ${DECOMPILE}
      CHANGELOGS: ${CHANGELOGS}
      PARSE: ${PARSE}
      WIKI_UPLOAD: ${WIKI_UPLOAD}
      FORCE: ${FORCE}
      CLEANUP: ${CLEANUP}
      VERBOSE: ${VERBOSE}
      STEAM_USERNAME: ${STEAM_USERNAME}
      STEAM_PASSWORD: ${STEAM_PASSWORD}
      BOT_WIKI_USER: ${BOT_WIKI_USER}
      BOT_WIKI_PASS: ${BOT_WIKI_PASS}
      # --- TEST-ONLY ---
      TEST_SINGLE_CHANGELOG_ID: ${TEST_SINGLE_CHANGELOG_ID}
      WIKI_SANDBOX_PAGE_TITLE: ${WIKI_SANDBOX_PAGE_TITLE}
      WIKI_TEST_OVERWRITE: ${WIKI_TEST_OVERWRITE}
    volumes:
      - "./game-data:/data"
      - "./decompiled-data:/work"
      - "./input-data:/input"
      - "./output-data:/output"
