version: '3'
services:
  deadbot:
    image: ghcr.io/deadlock-wiki/deadbot:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - "./decompiled-data:/work"
      - "./input-data:/input"
      - "./output-data:/output"
    #
    # - 'C:\Program Files (x86)\Steam\steamapps\common\Deadlock':'/data:ro'
    # - "/mnt/SteamLibrary/steamapps/common/Deadlock":"/data:ro"
