version: '3'
services:
  deadbot:
    image: ghcr.io/deadlock_wiki/deadbot
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      # runtime config
      DECOMPILE: true
      PARSE: true
      BOT_PUSH: false
      CLEANUP: true
    volumes:
      - "./decompiled-data:/work"
      - "./output-data:/output"
    #
    # - 'C:\Program Files (x86)\Steam\steamapps\common\Deadlock':'/data:ro'
    # - "/mnt/SteamLibrary/steamapps/common/Deadlock":"/data:ro"
