services:
  deadbot:
    image: ghcr.io/deadlock-wiki/deadbot:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      # runtime config
      DECOMPILE: ${DECOMPILE}
      CHANGELOGS: ${CHANGELOGS}
      PARSE: ${PARSE}
      WIKI_UPLOAD: ${WIKI_UPLOAD}
      CLEANUP: ${PARSE}
      VERBOSE: ${VERBOSE}
      BOT_WIKI_USER: ${BOT_WIKI_USER}
      BOT_WIKI_PASS: ${BOT_WIKI_PASS}
    volumes:
      - "./decompiled-data:/work"
      - "./input-data:/input"
      - "./output-data:/output"
    #
    # - 'C:\Program Files (x86)\Steam\steamapps\common\Deadlock':'/data:ro'
    # - "/mnt/SteamLibrary/steamapps/common/Deadlock":"/data:ro"
