services:
  deadbot:
    image: deadbot:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      IMPORT_FILES: ${IMPORT_FILES}
      ENGLISH_ONLY: ${ENGLISH_ONLY}
      DECOMPILE: ${DECOMPILE}
      CHANGELOGS: ${CHANGELOGS}
      PARSE: ${PARSE}
      WIKI_UPLOAD: ${WIKI_UPLOAD}
      FORCE: ${FORCE}
      CLEANUP: ${CLEANUP}
      VERBOSE: ${VERBOSE}
      STEAM_USERNAME: ${STEAM_USERNAME}
      STEAM_PASSWORD: ${STEAM_PASSWORD}
      BOT_WIKI_USER: ${BOT_WIKI_USER}
      BOT_WIKI_PASS: ${BOT_WIKI_PASS}
    volumes:
      - "./decompiled-data:/work"
      - "./input-data:/input"
      - "./output-data:/output"
    #
    # - 'C:\Program Files (x86)\Steam\steamapps\common\Deadlock':'/data:ro'
    # - "/mnt/SteamLibrary/steamapps/common/Deadlock":"/data:ro"
