# Maps page name in "Data:" namespace on the wiki to
# the file path in $OUTPUT_DIR
DATA_PAGE_FILE_MAP = {
    'AbilityCards.json': 'json/ability-cards.json',
    'AbilityData.json': 'json/ability-data.json',
    'AttributeData.json': 'json/attribute-data.json',
    'GenericData.json': 'json/generic-data.json',
    'HeroData.json': 'json/hero-data.json',
    'ItemData.json': 'json/item-data.json',
    'NpcData.json': 'json/npc-data.json',
    'Lang bg.json': 'localizations/bulgarian.json',
    'Lang cs.json': 'localizations/czech.json',
    'Lang da.json': 'localizations/danish.json',
    'Lang de.json': 'localizations/german.json',
    'Lang el.json': 'localizations/greek.json',
    'Lang en.json': 'localizations/english.json',
    'Lang es.json': 'localizations/spanish.json',
    'Lang es-419.json': 'localizations/latam.json',
    'Lang fi.json': 'localizations/finnish.json',
    'Lang fr.json': 'localizations/french.json',
    'Lang hu.json': 'localizations/hungarian.json',
    'Lang id.json': 'localizations/indonesian.json',
    'Lang it.json': 'localizations/italian.json',
    'Lang ja.json': 'localizations/japanese.json',
    'Lang ko.json': 'localizations/koreana.json',
    'Lang nl.json': 'localizations/dutch.json',
    'Lang no.json': 'localizations/norwegian.json',
    'Lang pl.json': 'localizations/polish.json',
    'Lang pt.json': 'localizations/portuguese.json',
    'Lang pt-br.json': 'localizations/brazilian.json',
    'Lang ro.json': 'localizations/romanian.json',
    'Lang ru.json': 'localizations/russian.json',
    'Lang sv.json': 'localizations/swedish.json',
    'Lang th.json': 'localizations/thai.json',
    'Lang tr.json': 'localizations/turkish.json',
    'Lang uk.json': 'localizations/ukrainian.json',
    'Lang vi.json': 'localizations/vietnamese.json',
    'Lang zh-hans.json': 'localizations/schinese.json',
    'Lang zh-hant.json': 'localizations/tchinese.json',
    'SoulUnlockData.json': 'json/soul-unlock-data.json',
    'StatInfoboxOrder.json': 'json/stat-infobox-order.json',
}

# Ignore these pages as they are not automated
IGNORE_PAGES = [
    'Dictionary',
    'Dictionary/sources',
    'Dictionary.json/sources',
    'LangCodes.json',
]
