name: CI
on: pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install Poetry
        run: pip install poetry

      - name: Install Ruff
        run: poetry install --only dev --no-root

      # Update output format to enable automatic inline annotations.
      - name: Run Ruff
        run: poetry run ruff check --output-format=github .
