name: Deploy
on: 
  push:
    branches: [ master, develop ]
  pull_request:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true
        default: 'develop'

jobs:
  # Each event type has a different variable for the branch name
  get-branch:
    name: Get branch name
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.branch.outputs.branch }}
    steps:
      - name: Branch used
        id: branch
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "push" ]]; then
            echo "::set-output name=branch::${{ github.ref_name  }}"
          elif [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
            echo "::set-output name=branch::${{ github.head_ref }}"
          elif [[ "${GITHUB_EVENT_NAME}" == "workflow_dispatch" ]]; then 
            echo "::set-output name=branch::${{ github.event.inputs.branch }}"
          else
            echo "::set-output name=branch::INVALID_EVENT_BRANCH_UNKNOWN"
          fi

  # Parse decompiled data stored on S3 and commit the changes to deadlock-data repo.
  # This repo is kept separate to keep the deadbot repo diff cleaner, whilst allowing
  # for easy source control and diff viewing.
  parse:
    name: Parse
    runs-on: ubuntu-latest
    needs: get-branch
    steps:
      - uses: actions/checkout@v4
        with:
          path: deadbot

      - name: Install docker-compose
        run: sudo apt-get install -y docker-compose

      - name: Build Deadbot
        run: docker-compose build
        working-directory: deadbot 
        env:
          IAM_KEY: ${{ secrets.IAM_KEY }}
          IAM_SECRET: ${{ secrets.IAM_SECRET }}
          BOT_WIKI_USER: ${{ secrets.BOT_WIKI_USER }}
          BOT_WIKI_PASS: ${{ secrets.BOT_WIKI_PASS }}
      
      - name: Run Deadbot
        run: docker-compose up
        working-directory: deadbot
        env:
          IMPORT_FILES: true
          DECOMPILE: false
          BOT_PUSH: ${{ needs.get-branch.outputs.branch }} == master

      - name: Checkout deadlock-data repo
        uses: actions/checkout@v4
        with:
          repository: deadlock-wiki/deadlock-data
          path: deadlock-data
          token:  ${{ secrets.GH_TOKEN }}          

      - name: Configure Git
        working-directory: deadlock-data 
        run: |
          git config --global user.email "deadbot1101@gmail.com"
          git config --global user.name "Deadbot0"
        
      - name: Switch to same branch name, create if not found
        working-directory: deadlock-data
        run: |
          git pull origin ${{ needs.get-branch.outputs.branch }} || echo "Ignoring non-existent branch ${{ needs.get-branch.outputs.branch }}"
          git switch -c ${{ needs.get-branch.outputs.branch }}
          git push --set-upstream origin ${{ needs.get-branch.outputs.branch }}

      - name: Pull branch
        working-directory: deadlock-data 
        run: git pull origin ${{ needs.get-branch.outputs.branch }} -X ours     

      - name: Copy files to data repo
        run: |
          rm -rf ./deadlock-data/data/current
          cp -r ./deadbot/output-data ./deadlock-data/data/current

      - name: Commit and push changes
        working-directory: deadlock-data 
        run: |
          git add -A
          git commit -m "Re-parsed game files" || echo "No changes to commit"
          git push origin ${{ needs.get-branch.outputs.branch }}
    
      - name: Install GH CLI
        if: github.event_name == 'pull_request' 
        run: sudo apt-get install -y gh

      # Creates a PR to enable viewing the outcome of the deadbot changes
      - name: Create a Pull Request
        if: github.event_name == 'pull_request' 
        id: create_data_pr
        working-directory: deadlock-data 
        run: |
          gh auth login --with-token <<< ${{ secrets.GH_TOKEN }}
          pr_url=$(
            gh pr create \
              --head ${{ needs.get-branch.outputs.branch }} \
              --base develop \
              --title ${{ needs.get-branch.outputs.branch }} \
              --body "_PR Auto-generated by [deadbot PR](https://github.com/deadlock-wiki/deadbot/pull/${{ github.event.number }})_"
              --json number | jq .number
          )
          echo "pr_url=$pr_url" >> $GITHUB_OUTPUT
  
      # for a newly made PR, add the reference into the PR body 
      - name: Reference deadlock-data PR in deadbot PR body
        if: github.event_name == 'pull_request' && steps.create_data_pr.outputs.pr_url != ''
        working-directory: deadbot 
        run: |
          gh pr edit ${{ github.event.number }} --body "_Parsed data in [deadlock-data PR](${{ steps.create_data_pr.outputs.pr_url }})_"  