name: Deploy
on: 
  push:
    branches:
      - develop
      - master
    paths:
      - 'src/**'
      - 'Dockerfile'
      - '.github/workflows/deploy.yaml'
      - 'poetry.lock'

  pull_request:
    types: [opened, reopened]
    paths:
      - 'src/**'
      - 'Dockerfile'
      - '.github/workflows/deploy.yaml'
      - 'poetry.lock'

  workflow_dispatch:
    inputs:
      english-only:
        type: boolean
        description: Only parse English localizations
        default: false
        
  workflow_call:
    inputs:
      # branch override used by auto-deploy.yaml, as the schedule only runs on the default branch
      branch-override:
        type: string
        required: true
      english-only:
        type: boolean
        default: false

    secrets:
      GH_TOKEN:
        required: true
      STEAM_USERNAME:
        required: true
      STEAM_PASSWORD:
        required: true
      BOT_WIKI_PASS:
        required: true

jobs:
  # Each event type has a different variable for the branch name
  get-branch:
    name: Get branch name
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.branch.outputs.branch }}
    steps:
      - name: Determine branch name
        id: branch
        run: |
          # override with input branch if it exists
          if [[ -n "${{ inputs.branch-override }}" ]]; then
            echo "branch=${{ inputs.branch-override }}" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_EVENT_NAME}" == "push" ]]; then
            echo "branch=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
            echo "branch=${{ github.head_ref }}" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_EVENT_NAME}" == "workflow_dispatch" ]]; then 
            echo "branch=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "branch=INVALID_EVENT_BRANCH_UNKNOWN" >> $GITHUB_OUTPUT
          fi

  check-branch:
    name: Check deadlock-data branch exists
    runs-on: ubuntu-latest
    needs: get-branch
    outputs:
      branch_exists: ${{ steps.branch.outputs.branch_exists }}
    steps:
      - name: Check if deadlock-data branch exists
        id: branch      
        run: |
          branch_exists=$(git ls-remote --heads https://${{ secrets.GH_TOKEN }}@github.com/deadlock-wiki/deadlock-data.git refs/heads/${{ needs.get-branch.outputs.branch }})
          if [ -z "$branch_exists" ]; then
            echo "Branch does not exist, skipping the rest of the job"
            echo "branch_exists=false" >> $GITHUB_OUTPUT
          else
            echo "branch_exists=true" >> $GITHUB_OUTPUT
          fi

  # Parse game data and commit the parsed output to deadlock-data repo. 
  # This repo is kept separate to keep the deadbot repo diff cleaner, whilst allowing
  # for easy source control and diff viewing
  parse:
    name: Parse
    runs-on: ubuntu-latest
    needs: [get-branch, check-branch]
    if: ${{ needs.check-branch.outputs.branch_exists == 'true' }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.get-branch.outputs.branch }}
          path: deadbot
          token:  ${{ secrets.GH_TOKEN }}     

      - name: Checkout deadlock-data repo
        uses: actions/checkout@v4
        with:
          repository: deadlock-wiki/deadlock-data
          path: deadlock-data
          token:  ${{ secrets.GH_TOKEN }}     

      - name: Configure Git for deadbot repo
        working-directory: deadbot 
        run: |
          git config --global user.email "deadbot1101@gmail.com"
          git config --global user.name "Deadbot0"
          git config --global --add safe.directory ./data
          git config pull.rebase true    

      - name: Configure Git for data repo
        working-directory: deadlock-data 
        run: |
          git config --global user.email "deadbot1101@gmail.com"
          git config --global user.name "Deadbot0"
          git config pull.rebase true     
        
      - name: Switch to same branch name on deadlock-data. If not found, skip job
        working-directory: deadlock-data
        run: |
          git fetch origin ${{ needs.get-branch.outputs.branch }}
          git switch ${{ needs.get-branch.outputs.branch }}
        continue-on-error: true  # Allow the job to stop if this step fails

      - uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Build Deadbot
        uses: docker/build-push-action@v6
        with:
          context: ./deadbot
          file: ./deadbot/Dockerfile
          push: false
          tags: deadbot:latest
          cache-from: |
            type=gha,scope=deadbot-master
            type=gha,scope=deadbot-${{ needs.get-branch.outputs.branch }}
          cache-to: type=gha,mode=max,scope=deadbot-${{ needs.get-branch.outputs.branch }}
          load: true   

      - name: Cache decompiled-data
        uses: actions/cache@v4
        with:
          path: deadbot/decompiled-data
          key: deadbot-decompiled-${{ hashFiles('deadbot/src/decompiler/**/*') }}
          restore-keys: deadbot-decompiled-

      - name: Run Deadbot
        working-directory: deadbot
        run: docker compose up --exit-code-from deadbot --abort-on-container-exit
        env:
          IMPORT_FILES: true
          ENGLISH_ONLY: ${{ github.event.inputs.english-only == 'true' }}
          PARSE_MAP: true
          DECOMPILE: true
          PARSE: true
          CHANGELOGS: true
          CLEANUP: false
          WIKI_UPLOAD: ${{ needs.get-branch.outputs.branch == 'master' }}
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
          BOT_WIKI_USER: ${{ vars.BOT_WIKI_USER }}
          BOT_WIKI_PASS: ${{ secrets.BOT_WIKI_PASS }}
          VERBOSE: ${{ secrets.ACTIONS_RUNNER_DEBUG == 'true' }}

      - name: Read versions
        id: read_versions
        working-directory: deadbot
        run: |
          DEADBOT_VERSION=$(grep -m1 '^version' pyproject.toml | sed 's/version *= *"\(.*\)"/\1/')
          echo "deadbot=$DEADBOT_VERSION" >> $GITHUB_OUTPUT
          
          DEADLOCK_VERSION=$(grep '^ClientVersion=' "./decompiled-data/version.txt" | cut -d'=' -f2 | tr -d '\r')
          echo "deadlock=$DEADLOCK_VERSION" >> $GITHUB_OUTPUT

          DATE=$(grep '^VersionDate=' "./decompiled-data/version.txt" | cut -d'=' -f2 | tr -d '\r')
          echo "date=$DATE" >> $GITHUB_OUTPUT
          
      - name: Commit and push input-data changes to deadbot
        working-directory: deadbot
        run: |
          git add input-data
          git commit -m "[skip ci] chore: updated input data" || echo "No changes to commit"
          git push --force-with-lease origin ${{ needs.get-branch.outputs.branch }}

      - name: Pull data branch
        working-directory: deadlock-data 
        run: git pull origin ${{ needs.get-branch.outputs.branch }} -X ours     

      - name: Copy files to data repo
        run: |         
          cp -r ./deadbot/output-data/. ./deadlock-data/data
      
      - name: Commit and push changes to data repo
        working-directory: deadlock-data
        env:
          DEADBOT_VER: ${{ steps.read_versions.outputs.deadbot }}
          DEADLOCK_VER: ${{ steps.read_versions.outputs.deadlock }}
          DATE: ${{ steps.read_versions.outputs.date }}
        run: |
          SHORT_SHA="${GITHUB_SHA::7}"          
          git add -A
          git commit -m "Deadbot v$DEADBOT_VER | Client $DEADLOCK_VER - $DATE (deadbot@${SHORT_SHA})" || echo "No changes to commit"
          git push --force-with-lease origin ${{ needs.get-branch.outputs.branch }}
  
  binary:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=gha,scope=deadbot-build-master
            type=gha,scope=deadbot-build-${{ env.BRANCH_NAME }}
          cache-to: type=gha,mode=max,scope=deadbot-build-${{ env.BRANCH_NAME }}
          
      - name: Build deadbot executable
        run: |         
          docker run --rm \
            -v ${{ github.workspace }}/dist:/repo/dist \
            --cpus=$(nproc) \
            --entrypoint bash \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} \
            -c "python3 -m nuitka ./src/deadbot.py \
                --static-libpython=no \
                --onefile \
                --output-dir=/dist \
                --jobs=$(nproc) \
                --lto=yes \
                --enable-plugin=anti-bloat \
                --python-flag=no_site \
                --python-flag=no_warnings \
                --include-data-dir=./src/parser/parsers/game_map/assets=parser/parsers/game_map/assets \
                --include-data-dir=./src/tools=tools \
                --include-data-files=./src/steam/steam_db_download_deadlock.sh=steam/steam_db_download_deadlock.sh \
                --include-data-files=./src/steam/depot_downloader_file_list.txt=steam/depot_downloader_file_list.txt"

      - name: Upload deadbot artifact
        uses: actions/upload-artifact@v4
        with:
          name: deadbot-${{ github.sha }}
          path: dist/deadbot
          if-no-files-found: error