name: Deploy
on: 
  push:
    branches: [ master, develop ]
  pull_request:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true
        default: 'develop'

jobs:
  get-branch:
    name: Get branch name
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.branch.outputs.branch }}
    steps:
      - name: Branch used
        id: branch
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "push" ]]; then
            echo "::set-output name=branch::${{ github.ref_name  }}"
          elif [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
            echo "::set-output name=branch::${{ github.head_ref }}"
          elif [[ "${GITHUB_EVENT_NAME}" == "workflow_dispatch" ]]; then 
            echo "::set-output name=branch::${{ github.event.inputs.branch }}"
          else
            echo "::set-output name=branch::INVALID_EVENT_BRANCH_UNKNOWN"
          fi

  parse:
    name: Parse
    runs-on: ubuntu-latest
    needs: get-branch
    steps:
      - uses: actions/checkout@v4
        with:
          path: deadbot

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install docker-compose
        run: sudo apt-get install -y docker-compose

      - name: Build Deadbot
        run: docker-compose build
        working-directory: deadbot 
        env:
          IAM_KEY: ${{ secrets.IAM_KEY }}
          IAM_SECRET: ${{ secrets.IAM_SECRET }}
          BOT_WIKI_USER: ${{ secrets.BOT_WIKI_USER }}
          BOT_WIKI_PASS: ${{ secrets.BOT_WIKI_PASS }}
      
      # - name: Run Deadbot
      #   run: docker-compose up
      #   working-directory: deadbot 

      - name: Checkout deadlock-data repo
        uses: actions/checkout@v4
        with:
          repository: deadlock-wiki/deadlock-data
          path: deadlock-data
          token:  ${{ secrets.GH_TOKEN }}
          
      - name: Switch to same branch name, create if not found
        working-directory: deadlock-data
        run: git switch -c ${{ needs.get-branch.outputs.branch }}

      - name: Copy files to data repo
        run: cp -r ./deadbot/output-data ./deadlock-data/data/current

      - name: Configure Git
        working-directory: deadlock-data 
        run: |
          git config --global user.email "deadbot1101@gmail.com"
          git config --global user.name "Deadbot0"
          
      - name: Commit and push changes
        working-directory: deadlock-data 
        run: |
          git branch --set-upstream-to=origin/${{ needs.get-branch.outputs.branch }}
          git fetch
          git pull
          git add -A
          git commit -m "Re-parsed game files" || echo "No changes to commit"
          git push origin HEAD  

      - name: Install GitHub CLI
        run: |
          sudo apt-get install -y gh

      - name: Create a Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh auth login --with-token <<< "$GITHUB_TOKEN" 
          gh pr create \
            --head ${{ needs.get-branch.outputs.branch }} \
            --base develop \
            --title ${{ needs.get-branch.outputs.branch }} \
            --body "_PR Auto-generated by [deadbot](https://github.com/deadlock-wiki/deadbot) repo_"