name: Increment Deadbot Version
on: 
  push:
    paths: 'src/**'
    branches:
      - 'develop'
  
  workflow_dispatch:
    inputs:
      type:
        description: 'Release type'
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
          - beta
          
jobs:
  increment-version:
    name: Increment Version
    runs-on: ubuntu-latest
    steps:
    - name: Checkout deadbot repo
      uses: actions/checkout@v4
      with:
        token:  ${{ secrets.GH_TOKEN }}

    - name: Configure Git
      run: |
        git config --global user.email "deadbot1101@gmail.com"
        git config --global user.name "Deadbot0"
        git config pull.rebase true    
    
    - name: Increment version
      run: python3 ./scripts/increment_version.py "${{ github.event.inputs.type != '' && github.event.inputs.type || 'beta' }}"

    - name: Commit updated version
      run: |
        git add pyproject.toml
        git commit -m "chore: incremented version" || echo "No changes to commit"
        git push --force-with-lease origin ${{ github.ref_name }}
