name: PR Opened

on:
  pull_request:
    types: [opened, reopened]

jobs:
  open-data-pr:
    name: Open deadlock-data PR
    runs-on: ubuntu-latest
    # prevent develop and master being changed by this script
    if: ${{ github.head_ref != 'develop' && github.head_ref != 'master' }}
    steps:
      - name: Checkout deadbot repo
        uses: actions/checkout@v4
        with:
          path: deadbot

      - name: Checkout deadlock-data repo
        uses: actions/checkout@v4
        with:
          repository: deadlock-wiki/deadlock-data
          path: deadlock-data
          token:  ${{ secrets.GH_TOKEN }}          

      - name: Configure Git
        working-directory: deadlock-data 
        run: |
          git config --global user.email "deadbot1101@gmail.com"
          git config --global user.name "Deadbot0"
          git config pull.rebase true

      - name: Create working branch on deadlock-data repo
        working-directory: deadlock-data 
        run: |
          git fetch origin
          
          if git ls-remote --exit-code --heads origin ${{ github.head_ref }}; then
            # branch exists, update local branch
            git switch ${{ github.head_ref }}
            git pull origin ${{ github.head_ref }} -X ours
          else
            # create new local branch
            git checkout -b ${{ github.head_ref }} origin/${{ github.event.pull_request.base.ref }}
          fi

          git commit --allow-empty -m "chore: empty commit to enable PR creation"
          git push --force-with-lease --set-upstream origin ${{ github.head_ref }}
      
      # Creates a PR to enable viewing the outcome of the deadbot changes
      - name: Create PR on deadlock-data repo
        id: create_data_pr
        working-directory: deadlock-data 
        run: |
          gh auth login --with-token <<< ${{ secrets.GH_TOKEN }}
          pr_url=$(
            gh pr create \
              --head ${{ github.head_ref }} \
              --base ${{ github.base_ref }} \
              --title ${{ github.head_ref }} \
              --body "_PR Auto-generated by [deadbot PR](https://github.com/deadlock-wiki/deadbot/pull/${{ github.event.number }})_"
          )
          echo "pr_url=$pr_url" >> $GITHUB_OUTPUT

      # for a newly made PR, add the reference into the PR body 
      - name: Reference deadlock-data PR in deadbot PR body
        if: steps.create_data_pr.outputs.pr_url != ''
        working-directory: deadbot 
        run: |
          current_body=$(gh pr view ${{ github.event.number }} --json body -q ".body")

          new_body="$current_body

          _Parsed data in [deadlock-data PR](${{ steps.create_data_pr.outputs.pr_url }})_"

          gh pr edit ${{ github.event.number }} --body "$new_body"  
