name: PR Opened

on:
  pull_request:
    types: [opened, reopened]

jobs:
  open-data-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout deadbot repo
        uses: actions/checkout@v4
        with:
          path: deadbot

      - name: Checkout deadlock-data repo
        uses: actions/checkout@v4
        with:
          repository: deadlock-wiki/deadlock-data
          path: deadlock-data
          token:  ${{ secrets.GH_TOKEN }}          

      - name: Create working branch on deadlock-data repo
        run: git switch -c ${{ needs.get-branch.outputs.branch }}

      # Creates a PR to enable viewing the outcome of the deadbot changes
      - name: Create PR on deadlock-data repo
        id: create_data_pr
        working-directory: deadlock-data 
        run: |
          gh auth login --with-token <<< ${{ secrets.GH_TOKEN }}
          pr_url=$(
            gh pr create \
              --head ${{ github.head_ref }} \
              --base develop \
              --title ${{ github.head_ref }} \
              --body "_PR Auto-generated by [deadbot PR](https://github.com/deadlock-wiki/deadbot/pull/${{ github.event.number }})_"
              --json number | jq .number
          )
          echo "pr_url=$pr_url" >> $GITHUB_OUTPUT

      # for a newly made PR, add the reference into the PR body 
      - name: Reference deadlock-data PR in deadbot PR body
        if: steps.create_data_pr.outputs.pr_url != ''
        working-directory: deadbot 
        run: |
          current_body=$(gh pr view ${{ github.event.number }} --json body -q ".body")

          new_body="$current_body

          _Parsed data in [deadlock-data PR](${{ steps.create_data_pr.outputs.pr_url }})_"

          gh pr edit ${{ github.event.number }} --body "$new_body"  
