name: PR Synchronize

on:
  pull_request:
    types: [synchronize]
    branches:
      - 'feature/*'
      - 'bugfix/*'
      - 'release/*'

jobs:
  update-pr:
    name: Update deadlock-data branch with base branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout deadlock-data repo
        uses: actions/checkout@v4
        with:
          repository: deadlock-wiki/deadlock-data
          path: deadlock-data
          token:  ${{ secrets.GH_TOKEN }}          

      - name: Configure Git
        working-directory: deadlock-data 
        run: |
          git config --global user.email "deadbot1101@gmail.com"
          git config --global user.name "Deadbot0"
          git config pull.rebase false

      - name: Switch to same branch name on deadlock-data
        working-directory: deadlock-data
        run: |
          git fetch origin ${{ github.head_ref }}
          git switch ${{ github.head_ref }}
          
      - name: Merge in target branch
        working-directory: deadlock-data 
        run: |
          git pull origin ${{ github.base_ref }} -X ours --allow-unrelated-histories   
          git push --force-with-lease origin ${{ github.head_ref }}
